version: '3'

services:
  todos-api:
    container_name: todos-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      HTTP_HOST: todos-api
      HTTP_PORT: 8080
      SQL_HOST: todos-api-db
      SQL_PORT: 5432
      SQL_USER: postgres
      SQL_PASS: postgres
      SQL_DBNAME: postgres
    depends_on: 
      todos-api-db:
        condition: service_healthy

  todos-api-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 15
